# Generated by Django 5.2.2 on 2025-10-22 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedString',
            fields=[
                ('sha256_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('properties', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
