# Generated by Django 5.2.2 on 2025-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedstring',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='analyzedstring',
            name='sha256_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='analyzedstring',
            name='text',
            field=models.TextField(),
        ),
    ]
